name: Build
description: Build application with Maven and create a new Docker image
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name for the generated Docker image"
    required: true
  tag_name:
    description: "Tag to be added to the final image"
    required: false

runs:
  using: composite
  steps:
    - run: |
        echo "Update me with the necessary steps to build the application"
      shell: bash
      
    - name: Determine Docker tag
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi

    - name: Create new Docker image
      shell: bash
      run: |
        if [ -z "${{ inputs.image_name }}" ]; then
            echo "DOCKER_IMAGE_NAME=$(date +%s)" >> $GITHUB_ENV
        else
            echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV
        fi
        docker build . --file "${{ inputs.path_dockerfile }}" --tag "${{ inputs.tag_name }}"

    - name: List Docker images
      shell: bash
      run: docker images
