name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - run: |
        echo "Update me with the necessary steps to build the application"
      shell: bash
    - name: Build with Maven
      shell: bash
      run: mvn -B package -DskipTests --file pom.xml
      